apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: my-demo-app-1
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: ["staging"]
 - targetId: qsprod
   profiles: ["production"]
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/<gcp_project_id>/locations/us-central1-f/clusters/quickstart-cluster-qsdev
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: qsprod
description: production cluster
gke:
 cluster: projects/<gcp_project_id>/locations/us-central1-f/clusters/quickstart-cluster-qsprod