apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-qs-dev
spec:
  template:
    spec:
      containers:
      - image: my-app-image
      # serviceAccountName:<SA_NAME>@<PROJECT_ID>.iam.gserviceaccount.com