name: clouddeploy-promote
on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  clouddeploy-promote:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloudrun-with-tf
    steps:
      # https://github.com/google-github-actions/setup-gcloud/blob/main/example-workflows/cloud-run/cloud-run.yml
      - name: Checkout
        uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      
      - name: Promote release
        run: |-
          PR_NUMBER=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')
          gcloud deploy releases promote --release=release-$PR_NUMBER \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --delivery-pipeline=test-app-backend \
            --region=us-central1 \
            --quiet